name: Check NIE Appointment

on:
  workflow_dispatch: 

jobs:
  check-appointment:
    runs-on: ubuntu-latest
    env:
      PROVINCE: ${{ secrets.PROVINCE }}
      PASSPORT_ID: ${{ secrets.PASSPORT_ID }}
      NAME: ${{ secrets.NAME }}
      YEAR_OF_BIRTH: ${{ secrets.YEAR_OF_BIRTH }}
      COUNTRY: ${{ secrets.COUNTRY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright browsers
        run: yarn playwright install
      - name: Run appointment check
        run: yarn start